dependencies {
    implementation(project(":modules:api"))
    implementation(project(":modules:core"))
    implementation(project(":modules:config"))
    implementation(project(":modules:registry"))
    implementation(project(":modules:assets"))
    implementation(project(":modules:animation"))
    implementation(project(":modules:gui"))
    implementation(project(":modules:world"))
    implementation(project(":modules:ai"))
    implementation(project(":modules:admin"))
    implementation(project(":modules:gameplay"))
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("org.yaml:snakeyaml:2.3")
}
